### PR TITLE
Add last day of month

### PR DESCRIPTION
**Pull request by rdehuyss**
Hi Ahmed,

as I saw your solution, I also added an extra option to add the last of month.

Hope you like it!

### CODE REVIEW

**Comment by asahaf** [comment]
Thanks, we need to make sure that we can handle the case when both last day of month and last specific day of the month are specified.

**Comment by asahaf** [comment]
The current solution is when the last day of the month is specified, the last week day of the month is ignored. Should we throw an exception of invalid expression if both are specified?

**Comment by rdehuyss** [comment]
That's indeed a good idea.

**Comment by asahaf** [comment]
could you please update the PR

**Comment by rdehuyss** [comment]
Done!

**Comment by asahaf** [comment]
great! thank you

**Pull request merged**
